language: node_js
node_js: '4.1.1'
sudo: false
cache:
  directories:
    - node_modules
addons:
  apt:
    packages:
      - libc6-dev
before_install:
- npm install -g npm@2
install:
- npm install
script:
  npm test

